name: meleu
description: "meu novo lar na web"

url: "http://meleu.github.io"
baseurl: "/"
keywords: linux, shell, C, programming, programacao, retropie, retroachievements, retrogames, linuxmint, archlinux, cygwin
author: "meleu"
email: "meleu arroba yahoo ponto com"
gravatar_hash: "3b630bd3a90def23e68ab2f04a86da5c"
github: "meleu"

markdown: kramdown
highlighter: rouge

# Site general settings
lang: "pt_BR"
lang_alternate: "en"

paginate: 5
paginate_path: "/page:num/"

# colocar as postagens "sob" o /blog
permalink: /blog/:year/:month/:day/:title

nav:
  - name: "about"
    href: "/about"
  - name: "blog"
    href: "/blog"
    
sass:
  style: :compressed
  
  defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
