name: meleu
title: meleu
description: "Tentando fazer do github meu novo lar na web"
tagline: "meu novo lar na web"

url: "http://meleu.github.io"
baseurl: "/"
keywords: linux, shell, C, programming, programacao, retropie, retroachievements, retrogames, linuxmint, archlinux, cygwin

author:
  name: "meleu"
  url: "http://meleu.github.io"
  email: "meleu arroba yahoo ponto com"
  
gravatar_hash: "3b630bd3a90def23e68ab2f04a86da5c"
github:
  repo: "https://github.com/meleu/meleu.github.io"

markdown: kramdown
highlighter: rouge

# Site general settings
lang: "pt_BR"
lang_alternate: "en"

paginate: 5
paginate_path: "/page:num/"

# colocar as postagens "sob" o /blog
permalink: /blog/:year/:month/:day/:title
